version: '3.1'

services:
  pg_db:
    container_name: pg_db
    image: postgres
    restart: always
    networks:
      - postgres
    environment:
      - POSTGRES_PASSWORD=pw
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    volumes:
      - ./DB_Init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "mymale@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "pw"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres
    volumes:
      - db-pgadmin:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

volumes:
  db-data:
  db-pgadmin: